### PR TITLE
Add the HAProxy exporter for Prometheus.

### PR DESCRIPTION
**Pull request by UmanShahzad**

### CODE REVIEW

**Review by smarnach — APPROVED** [review]
This looks good to me.  However, I'm not really an independent reviewer, since this is quite similar to the code I wrote.  Anyway, since you looked at it and I looked at it, we have two pairs of eyes, and I verified that the exporters are working fine, so :+1:.

**Comment by smarnach** [comment]
I just noticed that the integration tests are failing – they should of course be fixed before merging.

**Comment by UmanShahzad** [comment]
@smarnach Thanks! I'll just create a dummy role that should fit the purpose, since not having `nginx-proxy` is what's causing the issues.

**Comment by UmanShahzad** [comment]
@smarnach Just to confirm, are you okay with the method I used here to make the tests pass?

**Comment by smarnach** [comment]
@UmanShahzad Would simply setting `HAPROXY_EXPORTER_ENABLED` to false do the trick as well?  If so, I think that would be the simpler solution.  Otherwise I'm fine with what you have.

I initially tried to make this role usable completely stand-alone, outside of the context of our other roles, but since we recently moved to tighter integration between our roles it's fine to do this here as well.  The main part of the role should still work independent of ansible-playbooks, and we don't really need this anyway – it was just a nice-to-have.

**Comment by UmanShahzad** [comment]
@smarnach `HAPROXY_EXPORTER_ENABLED` is actually false by default, and I did that for this reason, to avoid test issues. But that didn't seem to solve it because I guess ansible looks for the role anyway, so oh well :(

(Of course, `HAPROXY_EXPORTER_ENABLED` is true in the group vars though).

**Comment by smarnach** [comment]
@UmanShahzad Oh, right, the `when` clause only applies to tasks.  Variables, handlers, dependencies etc. are processed independent of whether the condition is true or false, so I see it will look for the role in any case.  So yeah, what you have seems the easiest solution then.

**Pull request merged**
